webapp/urls.py
from django.urls import path,include
from . import views
app_name='webapp'

urlpatterns = [
    path('',views.Home, name='Home'),
    path('cform/',views.companyModelView, name='Cform'),
    path('delete/<int:id>/',views.delete_Company, name='deleteComp'),
    path('<int:id>/', views.edit_Company, name='Edit'),

]

templates/Table_creation.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-4">
        <h4 class="text-center alert alert-info">Fill to Add Company</h4>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary">
        </form>
    </div>
<br>
    <div class="col-sm-8">
        <h4 class="text-center alert alert-info">List of Company Details</h4>
        {% if stud %}

            <table class="table table-bordered">
  <thead>

  </thead>
  <tbody>
  {% for i in stud %}
    <tr>
        <th style="background-color: #4CAF50; color: white;"><h3>{{i.Company}}</h3></th>
        <th><a href="{% url 'webapp:Edit' i.id %}" class="btn btn-warning">Edit Company</a>
            <form action="{% url 'webapp:deleteComp' i.id%}" method="POST" class="d-inline">
                 {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Delete">
            </form>
        </th>

    </tr> <tr>
      <th scope="row">Division</th>
      <td>{{i.Division}}</td>
    </tr>

   <tr>
      <th scope="row">Sector</th>
      <td>{{i.Sector}}</td>
    </tr>
   <tr>
      <th scope="row">Phone</th>
      <td>{{i.Phone}}</td>
    </tr>
   <tr>
      <th scope="row">Fax</th>
      <td>{{i.Fax}}</td>
    </tr>
   <tr>
  <th scope="row">Website</th>
       <td><a href="{{i.Website}}" target="_blank">{{i.Website}}</a></td>
    </tr>
   <tr>
       <tr>
      <th scope="row">NAICS_codes</th>
      <td>{{i.NAICS_codes}}</td>
    </tr>
   <tr>
   <tr>
      <th scope="row">EstimatedPayroll</th>
      <td>{{i.EstimatedPayroll}}</td>
    </tr>
   <tr>
          <tr>
      <th scope="row">Number_Of_Employees</th>
      <td>{{i.Number_of_Employees}}</td>
    </tr>
   <tr>
          <tr>
      <th scope="row">Industry</th>
      <td>{{i.Industry}}</td>
    </tr>
   <tr>
          <tr>
      <th scope="row">Number_of_Internal_Employees</th>
      <td>{{i.Number_of_Internal_Employees}}</td>
    </tr>
   <tr>
          <tr>
      <th scope="row">Number_of_consultants_on_OPT</th>
      <td>{{i.Number_of_consultants_on_OPT}}</td>
    </tr>
   <tr>
          <tr>
      <th scope="row">Number_of_consultants_on_CTP</th>
      <td>{{i.Number_of_consultants_on_CPT}}</td>
    </tr>
   <tr>
          <tr>
      <th scope="row">Number_of_consultants_on_H1B</th>
      <td>{{i.Number_of_consultants_on_H1B}}</td>
    </tr>
   <tr>
          <tr>
      <th scope="row">Number_of_card_consultants</th>
      <td>{{i.Number_of_card_consultants}}</td>
    </tr>
   <tr>
          <tr>
      <th scope="row">Number_of_US_Citizens</th>
      <td>{{i.Number_of_US_Citizens}}</td>
    </tr>
   <tr>
          <tr>
      <th scope="row">Number_of_consultants_on_other_visa</th>
      <td>{{i.Number_of_consultants_on_other_visa}}</td>
    </tr>
   <tr>
      <th scope="row">AddressLine1</th>
      <td>{{i.AddressLine1}}</td>
    </tr>
   <tr>
      <th scope="row">AddressLine2</th>
      <td>{{i.AddressLine2}}</td>
    </tr>
<tr>
      <th scope="row">City</th>
      <td>{{i.City}}</td>
    </tr>
  <tr>
      <th scope="row">Zipcode</th>
      <td>{{i.Zipcode}}</td>
    </tr>
  <tr>
      <th scope="row">State</th>
      <td>{{i.State}}</td>
    </tr>
  <tr>
      <th scope="row">FederalID_EIN</th>
      <td>{{i.FederalID_EIN}}</td>
    </tr>
  <tr>
      <th scope="row">GST_Number</th>
      <td>{{i.GST_Number}}</td>
    </tr>
  <tr>
      <th scope="row">AddadditionalInformation</th>
      <td>{{i.AddadditionalInformation}}</td>
    </tr>
  </tbody>
                {% endfor %}
</table>

        {% else %}
        <h3 style="color: Red;" class="text-center"> No records</h3>
        {% endif %}
    </div>

</div>

{% endblock content%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
    <style>
        tr:nth-child(even) {background-color: #f2f2f2;}
    </style>
</head>
<body>
<div class="container mt-5 text-center">

<h4 class="alert alert-info">COMPANY INFORMATION</h4>
    </div>
<div class="container mt-5">
    <a href="{% url 'webapp:Home' %}" class="btn btn-primary">Home</a>
        <a href="{% url 'webapp:Cform' %}" class="btn btn-success">Dashboard</a>
    <a href="{% url 'webapp:Cform' %}" ><button class="btn btn-warning">Add Company</button></a>
    <br></div>
    <div class="container mt-5">
    {% if stud %}
        <h3 class="alert alert-info text-center">Dashboard</h3>
            <table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Company</th>
      <th scope="col">Division</th>
      <th scope="col">Sector</th>
      <th scope="col">Phone</th>
      <th scope="col">Website</th>
    </tr>
  </thead>
  <tbody>
  {% for i in stud %}
    <tr>
      <th scope="row">{{ i.Company }}</th>
      <td>{{ i.Division }}</td>
      <td>{{ i.Sector }}</td>
      <td>{{ i.Phone }}</td>
        <td><a href="{{i.Website}}" target="_blank">{{i.Website}}</a></td>
    </tr>
  </tbody>
{% endfor %}
</table>
    {% else %}
        <h3 style="color: Red;" class="text-center"> </h3><br><hr>
    {% endif %}
<br><hr class="alert alert-info">
    {% block content %}{% endblock content%}
<script src="{%static 'js/script1.js' %}"></script>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>


</html>

templates/update.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'webapp:Cform' %}" class="btn btn-success">Back to Dashboard</a>

<div class="row">
    <div class="col-sm-8 offset-2">
        <h4 class="alert alert-info">Update Fields</h4>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-success" value="Update" onclick="update()">
        </form>
    </div>

</div>

{% endblock content %}